
homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

app_genus_show:
    path: /genus/{genusName}
    defaults:
        _controller: AppBundle:Genus:show

app_genus_list:
    path: /genus
    defaults:
        _controller: AppBundle:Genus:list


app_genus_new:
    path: /genus/new
    defaults:
        _controller: AppBundle:Genus:new

app:
    resource: '@AppBundle/Controller/'
    type: annotation
